name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        run: make release
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            ./target/x86_64-unknown-linux-musl/release/https-check
